# Generated by Django 4.2.7 on 2023-11-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
