# Generated by Django 5.1 on 2024-08-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='CustomUsers',
        ),
    ]
